version: '3.8'

services:
  rag_api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./auth.json
        target: /app/api/data/auth.json
      - ./uploads:/app/uploads
    env_file:
      - .env

volumes:
  pgdata2:
