version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  fastapi:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_PROJECT_ID}  # 添加这个环境变量
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/api/data/auth.json  # 修改挂载方式
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata2:
