version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  fastapi:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - GOOGLE_APPLICATION_CREDENTIALS=/app/api/data/auth.json
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/api/data
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata2:
